[package]
name = "serde_derive_test"
version = "0.1.0"
authors = ["Robert Habermeier <rphmeier@gmail.com>"]

[dependencies]
test_macro = { path = "test_macro" }
serde_derive = "1.0"
serde = "1.0"

[workspace]
members = ["test_macro"]